version: '2'

services:

  wordpress:
    build:
      context: ./custom-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  nginx:
    build:
      context: ./custom-nginx
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  wpcli:
    image: wordpress:cli
    user: 33:33
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    command: >
      /bin/sh -c '
      sleep 10;
      if ! wp option get wpcli_setup_done; then
        wp core install --path="/var/www/html" --url="${WORDPRESS_URL}:${WORDPRESS_PORT}" --title="${WORDPRESS_SITE_TITLE}" --admin_user="${WORDPRESS_ADMIN_USER}" --admin_password="${WORDPRESS_ADMIN_PASSWORD}" --admin_email="${WORDPRESS_ADMIN_EMAIL}" --locale="es_ES" &&
        wp language core install es_ES &&
        wp site switch-language es_ES &&
        wp option update timezone_string "Europe/Madrid" &&
        wp option update date_format "d/m/Y" &&
        wp option update time_format "H:i" &&
        wp option update start_of_week 1 &&
        wp option update blog_public 0 &&
        wp rewrite structure '/%postname%/' --hard &&
        wp rewrite flush --hard &&
        wp plugin install ${WORDPRESS_PLUGINS} &&
        wp plugin update --all &&
        wp language plugin update --all &&
        wp theme delete twentytwentytwo &&
        wp theme delete twentytwentythree &&
        wp site empty --yes &&
        wp option add wpcli_setup_done 1;
      fi
      '
      
volumes:
  wordpress:
  db:
